--------------------------------------
-- SCHEMA
--------------------------------------
CREATE SCHEMA IF NOT EXISTS ACL1;

--------------------------------------
-- USUARIO
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.USUARIO (
    ID IDENTITY PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(254) NOT NULL,
    NOME VARCHAR(50),
    EMAIL VARCHAR(254) NOT NULL,
	LOCALIDADE VARCHAR(30),
	ORIGEM_ACESSO VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS UK01_USUARIO 
    ON ACL1.USUARIO(LOGIN);

--------------------------------------
-- PERFIL
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.PERFIL (
    ID IDENTITY PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(254)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK01_PERFIL 
    ON ACL1.PERFIL(NOME);

--------------------------------------
-- USUARIO_PERFIL
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.USUARIO_PERFIL (
    ID_USUARIO BIGINT NOT NULL,
    ID_PERFIL BIGINT NOT NULL
);

ALTER TABLE IF EXISTS ACL1.USUARIO_PERFIL 
  ADD CONSTRAINT PK_USUARIO_PERFIL PRIMARY KEY(ID_USUARIO, ID_PERFIL);

ALTER TABLE IF EXISTS ACL1.USUARIO_PERFIL 
  ADD CONSTRAINT FK01_USUARIO_PERFIL FOREIGN KEY(ID_USUARIO) REFERENCES ACL1.USUARIO(ID);

ALTER TABLE IF EXISTS ACL1.USUARIO_PERFIL 
  ADD CONSTRAINT FK02_USUARIO_PERFIL FOREIGN KEY(ID_PERFIL) REFERENCES ACL1.PERFIL(ID);

--------------------------------------
-- FUNCIONALIDADE
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.FUNCIONALIDADE (
    ID IDENTITY PRIMARY KEY AUTO_INCREMENT,
    ID_FUNCIONALIDADE BIGINT NULL,
    DESCRICAO VARCHAR(254),
    URL VARCHAR(255),
    ORDEM INT,
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE IF EXISTS ACL1.FUNCIONALIDADE 
  ADD CONSTRAINT FK01_FUNCIONALIDADE FOREIGN KEY(ID_FUNCIONALIDADE) REFERENCES ACL1.FUNCIONALIDADE(ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;  

--------------------------------------
-- EVENTO
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.EVENTO (
    ID IDENTITY PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(254),
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS UK01_EVENTO 
    ON ACL1.EVENTO(NOME);

--------------------------------------
-- FUNCIONALIDADE_EVENTO
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.FUNCIONALIDADE_EVENTO (
    ID_FUNCIONALIDADE BIGINT NOT NULL,
    ID_EVENTO BIGINT NOT NULL
);

ALTER TABLE IF EXISTS ACL1.FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT PK_FUNCIONALIDADE_EVENTO PRIMARY KEY(ID_FUNCIONALIDADE, ID_EVENTO);

ALTER TABLE IF EXISTS ACL1.FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT FK01_FUNCIONALIDADE_EVENTO FOREIGN KEY(ID_FUNCIONALIDADE) REFERENCES ACL1.FUNCIONALIDADE(ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

ALTER TABLE IF EXISTS ACL1.FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT FK02_FUNCIONALIDADE_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES ACL1.EVENTO(ID);

--------------------------------------
-- COMPONENTS
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.COMPONENTS (
    ID IDENTITY PRIMARY KEY AUTO_INCREMENT,
    ID_FUNCIONALIDADE BIGINT NOT NULL,
    PATH VARCHAR(254),
    NAME VARCHAR(100),
    COMPONENT VARCHAR(100),
    ICON VARCHAR(50),
    SIDEBAR BOOLEAN,
    COLLAPSED BOOLEAN
);

ALTER TABLE IF EXISTS ACL1.COMPONENTS 
  ADD CONSTRAINT FK01_COMPONENTS FOREIGN KEY(ID_FUNCIONALIDADE) REFERENCES ACL1.FUNCIONALIDADE(ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;  

--------------------------------------
-- COMPONENTS_FUNCIONALIDADE_EVENTO
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.COMPONENTS_FUNCIONALIDADE_EVENTO (
    ID_COMPONENTS BIGINT NOT NULL,
    ID_FUNCIONALIDADE BIGINT NOT NULL,
    ID_EVENTO BIGINT NOT NULL
);

ALTER TABLE IF EXISTS ACL1.COMPONENTS_FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT PK_COMPONENTS_FUNCIONALIDADE_EVENTO PRIMARY KEY(ID_COMPONENTS, ID_FUNCIONALIDADE, ID_EVENTO);

ALTER TABLE IF EXISTS ACL1.COMPONENTS_FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT FK01_COMPONENTS_FUNCIONALIDADE_EVENTO FOREIGN KEY(ID_COMPONENTS) REFERENCES ACL1.COMPONENTS(ID);

ALTER TABLE IF EXISTS ACL1.COMPONENTS_FUNCIONALIDADE_EVENTO 
  ADD CONSTRAINT FK02_COMPONENTS_FUNCIONALIDADE_EVENTO FOREIGN KEY(ID_FUNCIONALIDADE, ID_EVENTO) REFERENCES ACL1.FUNCIONALIDADE_EVENTO(ID_FUNCIONALIDADE, ID_EVENTO)
   ON DELETE CASCADE
   ON UPDATE CASCADE;   

--------------------------------------
-- PERMISSAO
--------------------------------------
CREATE TABLE IF NOT EXISTS ACL1.PERMISSAO (
    ID_PERFIL BIGINT NOT NULL,
    ID_FUNCIONALIDADE BIGINT NOT NULL,
    ID_EVENTO BIGINT NOT NULL
);

ALTER TABLE IF EXISTS ACL1.PERMISSAO 
  ADD CONSTRAINT PK_PERMISSAO PRIMARY KEY(ID_PERFIL, ID_FUNCIONALIDADE, ID_EVENTO);

ALTER TABLE IF EXISTS ACL1.PERMISSAO 
  ADD CONSTRAINT FK01_PERMISSAO FOREIGN KEY(ID_PERFIL) REFERENCES ACL1.PERFIL(ID);

ALTER TABLE IF EXISTS ACL1.PERMISSAO 
  ADD CONSTRAINT FK02_PERMISSAO FOREIGN KEY(ID_FUNCIONALIDADE, ID_EVENTO) REFERENCES ACL1.FUNCIONALIDADE_EVENTO(ID_FUNCIONALIDADE, ID_EVENTO);

  